### ISSUE TITLE
Startup 乐迪启动！

### ISSUE THREAD

**Issue by KC1zs4** [DongShanRoad99/JavaAssignment#2]
> zang zang这个issue出来就标志着我们的大作业启动了，这里说一下流程要怎么办

1. 我在issue取添加了一个plan label和一个milestone startup好像是，在最初一个星期9-10到9-17着差不多一个星期的时间里就是startup的阶段，我们对于像是代码风格文档（issue可以发文件）和项目项目的都使用issue进行讨论（我没开discussion），注意贴上标签和milestone，便于后期区分阶段
2. 我现在想的**第一个星期的打算**是
    1. 确认项目，同时确定技术栈
    2. 确定代码风格，建一个接口文档和各种原则比如面向接口，后面可以放到wiki里
    3. 项目确定后也别急着动手，先讨论出一个架构比如要用什么设计模式、类的设计这些这样，可以的话画画uml图这些
3. 上面的那些打算我有开对应的issue，集中到那一个issue中讨论就好了
4. 好像没什么想说的，就先这样吧

**Comment by coderYoga** [comment]
xsg好帅啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊
我还有几个想法：
1. 上面指的创建issue，是不是对于一类问题创建一个issue，比如说讨论项目的issue，然后在里面专门讨论这类问题，创建的时候创建为milestone然后加上plan标签
2. xsg发好issue之后可以在微信dd一下，现在还没养成看github的习惯
3. issue讨论可能有很多条，我们可以在创建issue的同时在wiki中创建一个md文档，记录这次issue讨论的结果
4. 我新开了一个专门用于讨论项目方案和技术栈的issue，然后在wiki里面也放了一个文档，xsg看看跟你的想法是不是一样的。

**Comment by KC1zs4** [comment]
1. 对的，就是一类issue
2. 豪德，我觉得issue只要在于记录，微信用来平时交流还是挺好的
3. 确实，差不多了就开始整理吧
4. ok我来康康
